---
# Source: my-app/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app
  labels:
    helm.sh/chart: my-app
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: whoami
  labels:
    helm.sh/chart: my-app
    app.kubernetes.io/name: whoami
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
