version: '3.9'

services:
  postgres:
    container_name: "my-app-db"
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
