apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app-deploy
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: my-app:2
          name: my-app
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: "my-app-db-postgresql.default.svc.cluster.local"
            - name: SECRET_NUMBER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: secret-number
          startupProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 6
            timeoutSeconds: 4
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 2
