apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: "my-app-db-postgresql.default.svc.cluster.local"
