apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: external-secrets
  name: scheduler-roles
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: external-secrets
  name: scheduler-rolebindings
subjects:
  - kind: ServiceAccount
    name: default
    namespace: external-secrets
roleRef:
  kind: Role
  name: scheduler-roles
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: external-secrets
  name: scale-up-external-secrets
spec:
  schedule: "5 10-12,15-18 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              args:
                - scale
                - deployment
                - -l
                - app.kubernetes.io/instance=external-secrets
                - --replicas=1
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: external-secrets
  name: scale-down-external-secrets
spec:
  schedule: "10 10-12,15-18 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              args:
                - scale
                - deployment
                - -l
                - app.kubernetes.io/instance=external-secrets
                - --replicas=0
          restartPolicy: OnFailure
