apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-es
spec:
  refreshInterval: 5s
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-app-css
  target:
    name: my-app-secrets
  data:
  - secretKey: secret-number
    remoteRef:
      key: secret-number
