apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app-svc
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 3000
