apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: my-app:1
          name: my-app
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_HOST
              value: "my-app-db-postgresql.default.svc.cluster.local"
            - name: SECRET_NUMBER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: secret-number
          startupProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 2
            failureThreshold: 2
