apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-tasks
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: curl
              image: "curlimages/curl:7.80.0"
              args:
                - "http://my-app-svc/periodic-task"
          restartPolicy: Never
