{{- range $app := $.Values.applications}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app.name }}-deploy
  labels:
    {{- include "my-app.labels" (list $ $app) }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" (list $ $app) | indent 2 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-app.selectorLabels" (list $ $app) | indent 4 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $.Chart.Name }}-sa
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $app.name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: {{ $app.repository | default $.Values.image.repository }}/{{ $app.image }}:{{ $app.tag | default $.Values.environment}}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $app.port | default 3000}}
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: {{ $app.db | default $.Values.db}}
          # PROBE #
          {{- include "my-app.probe" (list $ $app) }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
