{{- if .Values.ingress.traefik -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
{{- else -}}
apiVersion: extensions/v1beta1
kind: Ingress
{{- end }}
metadata:
  name: {{ .Chart.Name }}-ing
  labels: {{- include "my-app.labels" (list $ .) }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`my-app.localhost`) && Path(`/`)
      kind: Rule
      services:
        - name: my-app-svc
          port: 80
    - match: Host(`whoami.localhost`) && Path(`/`)
      kind: Rule
      services:
        - name: whoami-svc
          port: 80
