{{- range $app := .Values.applications}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}-svc
  labels: {{- include "my-app.labels" (list $ $app) }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" (list $ $app) | nindent 4 }}
---
{{- end}}
